### ISSUE TITLE
Pick a topic

### ISSUE THREAD

**Issue by kmoravej** [UBC-MDS/labzen#2]
Come up with a topic for your project. Discuss the topic with your TA or lab instructor and proceed only after your topic has been approved by one of them.

**Comment by rtaph** [comment]
Here is my first idea:

Package: mds-lab-utils-py and mds-lab-utils-r
A package to help MDS students manage their labs in iPython notebooks and R markdown.

- **Function 1 (Markdown Extractor)**: Parse an MDS .ipynd or .Rmd lab and return its markdown contents as a list/vector of strings (per line). Scrub out yaml, code blocks, and all other metadata.
- **Function 2 (Points Counter)**: Input markdown text from lab, parse into sections using regex, and determine how many optional and required points there are. Return a table of totals.
- **Function 3 (Mechanics Checker)**:
	- Check that you have included a Github repo link
	- Check that you have pushed the latest version
	- Check that you have at least three commits

**Comment by sukh2929** [comment]
Creating folder structure for R and Python projects
function 1 would be creating folders for the Python project 
function2  would be creating folders for the R project. 

We can add templates for a Team contract, contribution and code of conduct files as well in these functions

**Comment by kmoravej** [comment]
Making our own NN package:
- Loss Function
- Forward Propagation
- backward propagation

Depending on the complexity of package, we can add more function to improve the package. The problem with this is it would be challenging to implement it in R.

The second suggestion can be a package for wrangling data. This helps to have the same functionality between R and Python.
- Cleaning header name
- dropping NA
-  Imputing data with several options

**Comment by kmoravej** [comment]
We decided to go ahead with the package: mds-lab-utils-py and mds-lab-utils-r.
