### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by kmoravej** [UBC-MDS/labzen#4]
The name of the repositories should be relevant to the package/project topics.

**Comment by rtaph** [comment]
I propose the name `labzen` (Lab Zen). It is short and readable, and conveys the spirit of wanting to bring more zen to the stress otherwise brought forth by labs. What do you guys think?

![image](https://user-images.githubusercontent.com/9271253/109244910-6cd9a480-7794-11eb-963c-8d8a9c5aef9a.png)

**Comment by sukh2929** [comment]
This seems to be a nice, relatable name! :)

**Comment by kmoravej** [comment]
Awesome.  That is a great name!
