### ISSUE TITLE
Infer repo path from filename

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/labzen#61]
As per Craig's feedback:

>It might be nice to simplify the interface to your check_mechanics function. You're clearly doing a lot of extra processing behind the scenes with your private functions to get this to work. I realize this is more work, but it would be nice to have a similar interface to the count_points function with just a filename. The function would then figure out the rest, besides the token obviously!

It would be great if we could modify `check_mechanics()` so that it can also accept a file name as the first argument. The repo could be inferred from this.

**Comment by sukh2929** [comment]
working on this

**Comment by rtaph** [comment]
Addressed in #72
